---
# defaults file for development-server

java:
  jdk_version: 21

kubernetes:
  ports:
    api_server: 6443/tcp
    etcd: 2379-2380/tcp
    kubelet: 10250/tcp
    kube_scheduler: 10259/tcp
    kube_controller_manager: 10257/tcp
    kube_proxy: 10256/tcp
    node_port_services_tcp: 30000-32767/tcp
    node_port_services_udp: 30000-32767/udp