- name: Download k0s install script
  ansible.builtin.get_url:
    url: https://get.k0s.sh
    dest: /tmp/get.k0s.sh
    mode: '0755'

- name: Run k0s install script
  ansible.builtin.command: sh /tmp/get.k0s.sh
  become: true
  args:
    creates: /usr/local/bin/k0s

- name: Open kubernetes firewall ports
  # https://kubernetes.io/docs/reference/networking/ports-and-protocols/
  ansible.posix.firewalld:
    port: "{{ item.value }}"
    state: enabled
    permanent: true
    zone: internal
  with_dict: "{{ kubernetes.ports }}"
  notify: Reload firewalld

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0700'

- name: Install K9s
  ansible.builtin.dnf:
    name: k9s
    state: present
  become: true